name: Run Main Script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 23 * * 5"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: venv

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Altere para a versão desejada
          cache: "pip" # Acelera as futuras execuções salvando os pacotes em cache

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar o arquivo main.py
        env:
          USUARIO: ${{ secrets.USUARIO }}
          SENHA: ${{ secrets.SENHA }}
        run: python main.py

      # Passo responsável por salvar o JSON no repositório
      - name: Commitar e salvar o arquivo JSON gerado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: atualiza arquivo json [skip ci]"
          file_pattern: "*.json"
      # - name: Commitar e salvar o arquivo JSON gerado
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"

      #     # Substitua 'dados.json' pelo nome do seu arquivo ou '*.json'
      #     git add .

      #     # Só faz o commit se houver alguma alteração no arquivo
      #     git diff --quiet && git diff --staged --quiet || (git commit -m "bot: atualiza arquivo json [skip ci]" && git push)
